import {
  turkeyDate
} from "../../shared";

import {
  resolveArticleAdapter,
  resolveDirectAdapter
} from "./common";

import {
  acquireHttpFirstArticleHtml,
  resolveVerifiedArticleTargets
} from "./verified-article";

import {
  dateSearchText,
  raceDateParts,
  wordpressSearchUrl
} from "./article-url-utils";

import type {
  ExpertAdapter
} from "./types";


const ROOT =
  "https://istinyeganyan.com/";

const ARCHIVE =
  "https://istinyeganyan.com/kategori/at-yarisi/";

const CURRENT =
  "https://istinyeganyan.com/ganyan/tahminler/";


const MONTHS = [
  "OCAK",
  "ŞUBAT",
  "MART",
  "NİSAN",
  "MAYIS",
  "HAZİRAN",
  "TEMMUZ",
  "AĞUSTOS",
  "EYLÜL",
  "EKİM",
  "KASIM",
  "ARALIK"
];


const WEEKDAYS = [
  "PAZAR",
  "PAZARTESİ",
  "SALI",
  "ÇARŞAMBA",
  "PERŞEMBE",
  "CUMA",
  "CUMARTESİ"
];


function historicalUrl(
  city:string,
  raceDate:string
):string {
  const parts =
    raceDateParts(
      raceDate
    );

  const date =
    new Date(
      Date.UTC(
        parts.year,
        parts.month-1,
        parts.day,
        12
      )
    );

  const title =
    [
      parts.day,

      MONTHS[
        parts.month-1
      ],

      WEEKDAYS[
        date.getUTCDay()
      ],

      city.toLocaleUpperCase(
        "tr-TR"
      ),

      "ALTILI GANYAN TAHMİNLERİ"
    ]
      .join(" ");

  /*
   * Preserve combining marks generated by lowercasing
   * capital Turkish İ. This matches this site's WP slugs.
   */
  const slug =
    title
      .toLowerCase()
      .replace(
        /[^\p{L}\p{N}\p{M}]+/gu,
        "-"
      )
      .replace(
        /^-+|-+$/g,
        ""
      );

  return new URL(
    `${slug}/`,
    ROOT
  ).toString();
}


function ownsHistorical(
  value:string
):boolean {
  try {
    const url =
      new URL(value);

    const host =
      url.hostname
        .replace(/^www\./,"")
        .toLowerCase();

    const currentPath =
      new URL(
        CURRENT
      )
        .pathname;

    return (
      host ===
        "istinyeganyan.com" &&
      url.pathname !==
        currentPath &&
      !url.pathname
        .toLowerCase()
        .startsWith(
          "/kategori/"
        )
    );

  } catch {
    return false;
  }
}


export const istinyeGanyanAdapter:
  ExpertAdapter = {
    sourceKey:
      "istinye_ganyan",

    async resolve(context) {
      if (
        context.raceDate >=
        turkeyDate()
      ) {
        return resolveDirectAdapter(
          context
        );
      }

      const primary =
        await resolveVerifiedArticleTargets(
          context,
          {
            sourceKey:
              "istinye_ganyan",

            sourceName:
              "İstinye Ganyan",

            ownsArticle:
              ownsHistorical,

            directCandidates(
              ctx
            ) {
              return ctx.cities
                .map(
                  city => ({
                    city,

                    url:
                      historicalUrl(
                        city,
                        ctx.raceDate
                      )
                  })
                );
            },

            discoveryUrls(
              ctx
            ) {
              return [
                ...ctx.cities.map(
                  city =>
                    wordpressSearchUrl(
                      ROOT,
                      dateSearchText(
                        ctx.raceDate,
                        city
                      )
                    )
                ),

                ARCHIVE
              ];
            },

            maxCandidates:6,
            maxVerifiedPerCity:1,

            allowPuppeteerDiscovery:false,
            allowPuppeteerArticle:false,

            fallback:"none"
          }
        );

      if (
        primary.status ===
        "ready"
      ) {
        return primary;
      }

      const feed =
        await resolveArticleAdapter(
          context,
          {
            landingUrls:[],
            allowGeneric:false,
            allowFeed:true,
            verifyTargets:true,
            requireCityCoverage:true
          }
        );

      if (
        feed.status ===
        "ready"
      ) {
        return {
          ...feed,

          diagnostics:{
            primary:
              primary.diagnostics,

            feed:
              feed.diagnostics
          }
        };
      }

      return {
        ...primary,

        diagnostics:{
          primary:
            primary.diagnostics,

          feed:
            feed.diagnostics
        }
      };
    },

    ownsAcquisition(
      url
    ) {
      return ownsHistorical(
        url
      );
    },

    acquireHtml(context) {
      return acquireHttpFirstArticleHtml(
        context,
        {
          allowPuppeteer:false
        }
      );
    }
  };
